// <auto-generated />
using System;
using Its.Onix.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace onix.api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251026125107_Entity_Content_001")]
    partial class Entity_Content_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Its.Onix.Api.Models.MApiKey", b =>
                {
                    b.Property<Guid?>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key_id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<DateTime?>("KeyCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_created_date");

                    b.Property<string>("KeyDescription")
                        .HasColumnType("text")
                        .HasColumnName("key_description");

                    b.Property<DateTime?>("KeyExpiredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_expired_date");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("RolesList")
                        .HasColumnType("text")
                        .HasColumnName("roles_list");

                    b.HasKey("KeyId");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MAuditLog", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<string>("ApiName")
                        .HasColumnType("text")
                        .HasColumnName("api_name");

                    b.Property<string>("CfClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip_cf");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<string>("ControllerName")
                        .HasColumnType("text")
                        .HasColumnName("controller_name");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomDesc")
                        .HasColumnType("text")
                        .HasColumnName("custom_desc");

                    b.Property<string>("CustomStatus")
                        .HasColumnType("text")
                        .HasColumnName("custom_status");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("Host")
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<string>("IdentityType")
                        .HasColumnType("text")
                        .HasColumnName("identity_type");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Pin")
                        .HasColumnType("text")
                        .HasColumnName("pin");

                    b.Property<string>("QueryString")
                        .HasColumnType("text")
                        .HasColumnName("query_string");

                    b.Property<long?>("RequestSize")
                        .HasColumnType("bigint")
                        .HasColumnName("request_size");

                    b.Property<long?>("ResponseSize")
                        .HasColumnType("bigint")
                        .HasColumnName("response_size");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Scheme")
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<string>("Serial")
                        .HasColumnType("text")
                        .HasColumnName("serial");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MCycle", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("CycleType")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("StargDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<double?>("CreditAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("credit_amount");

                    b.Property<int?>("CreditTermDay")
                        .HasColumnType("integer")
                        .HasColumnName("credit_term_day");

                    b.Property<int?>("EntityCategory")
                        .HasColumnType("integer")
                        .HasColumnName("entity_category");

                    b.Property<int?>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NationalCardId")
                        .HasColumnType("text")
                        .HasColumnName("national_card_id");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text")
                        .HasColumnName("primary_email");

                    b.Property<string>("SecondaryEmail")
                        .HasColumnType("text")
                        .HasColumnName("secondary_email");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("TaxId")
                        .HasColumnType("text")
                        .HasColumnName("tax_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.HasIndex("OrgId", "PrimaryEmail")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MItem", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<string>("Narrative")
                        .HasColumnType("text")
                        .HasColumnName("narrative");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MItemImage", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_image_id");

                    b.Property<int?>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("FileSizeByte")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("file_size_byte");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer")
                        .HasColumnName("image_height");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer")
                        .HasColumnName("image_width");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Narative")
                        .HasColumnType("text")
                        .HasColumnName("narative");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<int?>("SortingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sorting_order");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MJob", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_cnt");

                    b.Property<string>("JobMessage")
                        .HasColumnType("text")
                        .HasColumnName("job_message");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_date");

                    b.Property<int?>("ProgressPct")
                        .HasColumnType("integer")
                        .HasColumnName("progress_pct");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("SucceedCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeed_cnt");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MMasterRef", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("master_ref_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<int?>("RefType")
                        .HasColumnType("integer")
                        .HasColumnName("ref_type");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.ToTable("MasterRefs");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MOrganization", b =>
                {
                    b.Property<Guid?>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("OrgCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("org_created_date");

                    b.Property<string>("OrgCustomId")
                        .HasColumnType("text")
                        .HasColumnName("org_custom_id");

                    b.Property<string>("OrgDescription")
                        .HasColumnType("text")
                        .HasColumnName("org_description");

                    b.Property<string>("OrgName")
                        .HasColumnType("text")
                        .HasColumnName("org_name");

                    b.HasKey("OrgId");

                    b.HasIndex("OrgCustomId")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MOrganizationUser", b =>
                {
                    b.Property<Guid?>("OrgUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_user_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("InvitedBy")
                        .HasColumnType("text")
                        .HasColumnName("invited_by");

                    b.Property<DateTime?>("InvitedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_date");

                    b.Property<string>("IsOrgInitialUser")
                        .HasColumnType("text")
                        .HasColumnName("is_org_initial_user");

                    b.Property<string>("OrgCustomId")
                        .HasColumnType("text")
                        .HasColumnName("org_custom_id");

                    b.Property<string>("OrgDesc")
                        .HasColumnType("text");

                    b.Property<string>("OrgName")
                        .HasColumnType("text");

                    b.Property<string>("PreviousUserStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_user_status");

                    b.Property<string>("RolesList")
                        .HasColumnType("text")
                        .HasColumnName("roles_list");

                    b.Property<string>("TmpUserEmail")
                        .HasColumnType("text")
                        .HasColumnName("tmp_user_email");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<string>("UserStatus")
                        .HasColumnType("text")
                        .HasColumnName("user_status");

                    b.HasKey("OrgUserId");

                    b.HasIndex("OrgCustomId");

                    b.HasIndex(new[] { "OrgCustomId", "UserId" }, "OrgUser_Unique1")
                        .IsUnique();

                    b.ToTable("OrganizationsUsers");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MPricingPlan", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("StargDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CycleId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique();

                    b.ToTable("PricingPlans");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MPricingPlanItem", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_item_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<double?>("FlateRate")
                        .HasColumnType("double precision")
                        .HasColumnName("flate_rate");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("PricingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_plan_id");

                    b.Property<string>("RateDefinition")
                        .HasColumnType("text")
                        .HasColumnName("rate_definition");

                    b.Property<int?>("RateType")
                        .HasColumnType("integer")
                        .HasColumnName("rate_type");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("PricingPlanId");

                    b.ToTable("PricingPlanItems");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MRole", b =>
                {
                    b.Property<Guid?>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("RoleCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_created_date");

                    b.Property<string>("RoleDefinition")
                        .HasColumnType("text")
                        .HasColumnName("role_definition");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("text")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_level");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MScanItem", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scan_item_id");

                    b.Property<string>("AppliedFlag")
                        .HasColumnType("text")
                        .HasColumnName("applied_flag");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ItemGroup")
                        .HasColumnType("text")
                        .HasColumnName("item_group");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("Pin")
                        .HasColumnType("text")
                        .HasColumnName("pin");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<string>("RegisteredFlag")
                        .HasColumnType("text")
                        .HasColumnName("registered_flag");

                    b.Property<string>("RunId")
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<int?>("ScanCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_count");

                    b.Property<string>("SequenceNo")
                        .HasColumnType("text")
                        .HasColumnName("sequence_no");

                    b.Property<string>("Serial")
                        .HasColumnType("text")
                        .HasColumnName("serial");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("UploadedPath")
                        .HasColumnType("text")
                        .HasColumnName("uploaded_path");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("UsedFlag")
                        .HasColumnType("text")
                        .HasColumnName("used_flag");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Serial")
                        .IsUnique();

                    b.HasIndex("OrgId", "Serial", "Pin")
                        .IsUnique();

                    b.ToTable("ScanItems");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MScanItemAction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("EncryptionIV")
                        .HasColumnType("text")
                        .HasColumnName("encryption_iv");

                    b.Property<string>("EncryptionKey")
                        .HasColumnType("text")
                        .HasColumnName("encryption_key");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("redirect_url");

                    b.Property<string>("RegisteredAwareFlag")
                        .HasColumnType("text")
                        .HasColumnName("registered_aware_flag");

                    b.Property<string>("ThemeVerify")
                        .HasColumnType("text")
                        .HasColumnName("theme_verify");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("ScanItemActions");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MScanItemTemplate", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("GeneratorCount")
                        .HasColumnType("integer")
                        .HasColumnName("generator_count");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("text")
                        .HasColumnName("noti_email");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<int?>("PinDigit")
                        .HasColumnType("integer")
                        .HasColumnName("pin_digit");

                    b.Property<int?>("SerialDigit")
                        .HasColumnType("integer")
                        .HasColumnName("serial_digit");

                    b.Property<int?>("SerialPrefixDigit")
                        .HasColumnType("integer")
                        .HasColumnName("serial_prefix_digit");

                    b.Property<string>("UrlTemplate")
                        .HasColumnType("text")
                        .HasColumnName("url_template");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("ScanItemTemplates");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MStat", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stat_id");

                    b.Property<long?>("BalanceBegin")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_begin");

                    b.Property<DateTime?>("BalanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("balance_date");

                    b.Property<string>("BalanceDateKey")
                        .HasColumnType("text")
                        .HasColumnName("balance_date_key");

                    b.Property<long?>("BalanceEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_end");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("StatCode")
                        .HasColumnType("text")
                        .HasColumnName("stat_code");

                    b.Property<long?>("TxIn")
                        .HasColumnType("bigint")
                        .HasColumnName("tx_in");

                    b.Property<long?>("TxOut")
                        .HasColumnType("bigint")
                        .HasColumnName("tx_out");

                    b.HasKey("Id");

                    b.HasIndex("BalanceDate");

                    b.HasIndex("OrgId");

                    b.HasIndex("StatCode");

                    b.HasIndex("OrgId", "StatCode", "BalanceDateKey")
                        .IsUnique();

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MSystemVariable", b =>
                {
                    b.Property<Guid?>("VariableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("variable_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("VariableName")
                        .HasColumnType("text")
                        .HasColumnName("varaible_name");

                    b.Property<string>("VariableValue")
                        .HasColumnType("text")
                        .HasColumnName("varaible_value");

                    b.HasKey("VariableId");

                    b.ToTable("MSystemVariables");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MUser", b =>
                {
                    b.Property<Guid?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("IsOrgInitialUser")
                        .HasColumnType("text")
                        .HasColumnName("is_org_initial_user");

                    b.Property<DateTime?>("UserCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_created_date");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MItemImage", b =>
                {
                    b.HasOne("Its.Onix.Api.Models.MItem", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MPricingPlan", b =>
                {
                    b.HasOne("Its.Onix.Api.Models.MEntity", "Customer")
                        .WithMany("PricingPlans")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Its.Onix.Api.Models.MCycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId");

                    b.Navigation("Customer");

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MPricingPlanItem", b =>
                {
                    b.HasOne("Its.Onix.Api.Models.MItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Its.Onix.Api.Models.MPricingPlan", "PricingPlan")
                        .WithMany("PricingPlanItems")
                        .HasForeignKey("PricingPlanId");

                    b.Navigation("Item");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MEntity", b =>
                {
                    b.Navigation("PricingPlans");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Its.Onix.Api.Models.MPricingPlan", b =>
                {
                    b.Navigation("PricingPlanItems");
                });
#pragma warning restore 612, 618
        }
    }
}
