#!/bin/bash

export $(grep -v '^#' .env | xargs)

ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHOTV2ajMtZDlJQ0otNEJuZ09iUkY2MVlpNzBMR01jQkpuZklISmFoRkFJIn0.eyJleHAiOjE3NTg2MzMzMTksImlhdCI6MTc1ODYzMzAxOSwianRpIjoiNzFhMmIxYmMtNzVhMC00NDQyLWEzMjktODQxZTQ5MDhjMzBlIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLXByb2R1Y3Rpb24taHR0cC5rZXljbG9hay5zdmMuY2x1c3Rlci5sb2NhbC9hdXRoL3JlYWxtcy9vbml4LXYyLWRldiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIwYmE2ZmQ4MS1iMTI1LTRlOTgtODRjNS03OTc0NzQ0ZGI4MmMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbGVhc2Utc2NhbiIsInNlc3Npb25fc3RhdGUiOiI3OTY4NTgxOS0wYzFkLTQ4ZGQtODA3NS05MDM5MWNjZTY5ODIiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1vbml4LXYyLWRldiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsInNpZCI6Ijc5Njg1ODE5LTBjMWQtNDhkZC04MDc1LTkwMzkxY2NlNjk4MiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlBqYW1lIFBsZWFzZS1TY2FuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicGphbWUxNiIsImdpdmVuX25hbWUiOiJQamFtZSIsImxvY2FsZSI6ImVuIiwiZmFtaWx5X25hbWUiOiJQbGVhc2UtU2NhbiIsImVtYWlsIjoicGphbWUxNi5mYkBnbWFpbC5jb20ifQ.WK8MwTh87POSEQWL01dgjNhT17iebnuGpzRzsQvRlIXz74jj-5sbdxK9hOD-1zZGjv0J8TzuBBOVmaHt0LaeS4dNQzemUmXmLDooRmS3ml6Ue798xnMDVbpJIcTpASLPnLAyeV2sjMVI6ecn02yqQAsg25g9NONfnpsZ5bzBCrnAG2lFiNjLZ3tw_uJ9rqeqpm2VcqPzHljhHPGG30E0SOc4fBXVFAnJqo1NfmN8w-KrdnXKHsQ_GsQZ6taxJiyQh-AKx1tXFUO4fRISw3B8w6po8vlrx5c5cxuICWuZU6IfK_PzylRSw5XApZDfyxrAmXXSkkE-xcBC7FGwALiIFg"
ACCESS_TOKEN_B64=$(echo -n "${ACCESS_TOKEN}" | base64 -w0)

#curl -s -X GET ${API_HTTP_ENDPOINT}/api/Organization/org/${API_ORG}/action/GetUserAllowedOrg \
#-H "Content-Type: application/json" -v -u "dummy:${API_KEY}"

API_ENDPOINT='/api/User/org/temp/action/UpdatePassword'

curl -s -X POST "${API_HTTP_ENDPOINT}${API_ENDPOINT}" \
-H "Content-Type: application/json" -v \
-H "Authorization: Bearer ${ACCESS_TOKEN_B64}" \
-d @update-password.json \

#curl -s -X POST https://keycloak.devops.napbiotec.io/auth/realms/onix-v2-dev/account/credentials/password \
#-H "Content-Type: application/json" -v \
#-H "Authorization: Bearer ${ACCESS_TOKEN}" \
#-d @update-password.json \
