#!/bin/bash

export $(grep -v '^#' .env | xargs)

ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHOTV2ajMtZDlJQ0otNEJuZ09iUkY2MVlpNzBMR01jQkpuZklISmFoRkFJIn0.eyJleHAiOjE3NTkxMTAyMTIsImlhdCI6MTc1OTEwOTkxMiwianRpIjoiMGQ1MjlkYzctZjkzMy00MDBlLTk0MWYtMDU2YTNjMmQ1MTkxIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLXByb2R1Y3Rpb24taHR0cC5rZXljbG9hay5zdmMuY2x1c3Rlci5sb2NhbC9hdXRoL3JlYWxtcy9vbml4LXYyLWRldiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIwYmE2ZmQ4MS1iMTI1LTRlOTgtODRjNS03OTc0NzQ0ZGI4MmMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbGVhc2Utc2NhbiIsInNlc3Npb25fc3RhdGUiOiI2MDc2MDE3MS1hNDNiLTRiNTQtOGUyNS02OTQ1ODc4ZjExNTciLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1vbml4LXYyLWRldiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsInNpZCI6IjYwNzYwMTcxLWE0M2ItNGI1NC04ZTI1LTY5NDU4NzhmMTE1NyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlBqYW1lIFBsZWFzZS1TY2FuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicGphbWUxNiIsImdpdmVuX25hbWUiOiJQamFtZSIsImxvY2FsZSI6ImVuIiwiZmFtaWx5X25hbWUiOiJQbGVhc2UtU2NhbiIsImVtYWlsIjoicGphbWUxNi5mYkBnbWFpbC5jb20ifQ.C0_NrgkIpUgrrVfIXtjofjn4-HtfMidfxb0AKXVMlwaIRiT70zIDkTp1bhzuwn4ozbY82aZhnFFvNDz-1BSGjEcObxaKrGAiMY7X77OkS2rWISvxlJw6d2KFY7Mc8xNAlon2hyQ5Wxn_pdcnkcnejr4_NkyKRzBboF7Tab5iw63-y20cRFBt_I4dwCCtvFAFFGPBlBhxZi-GJ7rSrLeVrx5e7MECA0fXsREQqNlrCcB0K0dCHCKSz3m8CQXIworfczh3_BBkewFnOPUMIHxT80w5s1CNx2y7LuqY3PPlho-CBlZyNSC-YlweJrXYQcJcfpmNyCHB5rGlgglfQoAQxQ"
ACCESS_TOKEN_B64=$(echo -n "${ACCESS_TOKEN}" | base64 -w0)

#curl -s -X GET ${API_HTTP_ENDPOINT}/api/OnlyUser/org/${API_ORG}/action/GetUserAllowedOrg \
#-H "Content-Type: application/json" -v -u "dummy:${API_KEY}"

curl -s -X GET ${API_HTTP_ENDPOINT}/api/OnlyUser/org/temp/action/GetUserAllowedOrg \
-H "Content-Type: application/json" -v \
-H "Authorization: Bearer ${ACCESS_TOKEN_B64}"
